language: ruby
rvm:
  # MRI
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - 2.3.0
  # JRuby
  - jruby-9000
script:
  # Tests
  - ruby tests/biscuit.rb
  # Examples
  - ruby Hype.rb examples/axiom/axiom.ujshop examples/axiom/pb1.ujshop run
  - ruby Hype.rb examples/cookie/cookie.ujshop examples/cookie/pb1.ujshop run
  - ruby Hype.rb examples/counter/counter.ujshop examples/counter/pb1.ujshop run
  - ruby Hype.rb examples/jumpmaze/jumpmaze.ujshop examples/jumpmaze/pb1.ujshop run