language: ruby
rvm:
  # MRI
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - 2.3.0
  # JRuby
  - jruby-9000
script:
  # Tests
  - ruby tests/biscuit.rb
  # Examples
  - ruby Hype.rb examples/cookie/cookie.ndjshop examples/cookie/pb1.ndjshop run