language: ruby
rvm:
  # MRI
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - 2.3.0
  # JRuby
  - jruby-9000
before_script:
  - git clone https://github.com/Maumagnaguagno/HyperTensioN.git ../HyperTensioN
  - git clone https://github.com/Maumagnaguagno/Polygonoid.git ../Polygonoid
script:
  # Tests
  - ruby tests/sphygmomanometer.rb
  - ruby tests/biscuit.rb
  - ruby tests/postulate.rb
  - ruby tests/path.rb
  - ruby tests/caller.rb
  # Examples
  - ruby Hype.rb examples/axiom/axiom.ujshop examples/axiom/pb1.ujshop run
  - ruby Hype.rb examples/cookie/cookie.ujshop examples/cookie/pb1.ujshop run
  - ruby Hype.rb examples/counter/counter.ujshop examples/counter/pb1.ujshop run
  - ruby Hype.rb examples/counter/counter.ujshop examples/counter/pb2.ujshop run
  - ruby Hype.rb examples/external/external.ujshop examples/external/pb1.ujshop run
  - ruby Hype.rb examples/jumpmaze/jumpmaze.ujshop examples/jumpmaze/pb1.ujshop run
  - ruby Hype.rb examples/search_angle/search.ujshop examples/search_angle/pb1.ujshop run
  - ruby Hype.rb examples/search_circular/search.ujshop examples/search_circular/pb1.ujshop run
  - ruby Hype.rb examples/search_circular/search.ujshop examples/search_circular/pb2.ujshop run 1
  - ruby examples/healthcare/pbhealthcare.ujshop.rb
  - ruby examples/healthcare/pbhealthcare_test_steps.ujshop.rb