language: ruby
rvm:
  # MRI
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - 2.3.0
  # JRuby
  - jruby-9000
  # Rubinius
  - rbx-2
before_script:
  - ls
  - ruby -e "path = File.expand_path('../HyperTensioN_ND', __FILE__); puts path; require path"
script:
  # Tests
  - ruby tests/biscuit.rb
  # Examples
  - ruby Hype.rb examples/cookie/cookie.ndjshop examples/cookie/pb1.ndjshop run